### ISSUE TITLE
Allow to enter path characters ("Alt Gr") in Windows

### ISSUE THREAD

**Issue by JonasLuerig** [MalteT/2a-emulator#2]
In the version running on Windows it is not possible to enter characters which are reached by pressing "Alt Gr" before. Since the path structure in Windows uses the backslash and at a german keyboard layout it is reached by this, the "load"-command does not allow to load files which are not in the same directory as the emulator.

**Comment by MalteT** [comment]
Could you execute `RUST_LOG=trace 2a-emulator 2>log.txt` and check what key events are generated or simply send the log file? I couldn't replicate your issue on my linux machine.

**Comment by MalteT** [comment]
I cannot test this myself, but I tried to fix it. I'll reopen this, if it turns out to still need fixing.
