### ISSUE TITLE
POPF does not write into FR

### ISSUE THREAD

**Issue by AlexVonB** [MalteT/2a-emulator#22]
Hi Malte!

One of our students found this problem: when PUSHF-ing the flags (which works) and then POPF-ing, the flag register does not get restored. Do you know this problem? Is it an user error? :D

```asm
#! mrasm

	LDSP 0xEF	; Load stack pointer, to enable calls
	CLR R0		; Clear register 0

MAIN:
	LD R0, 1
	LSR R0		; set Carry Flag

	PUSHF		; push Carry Flag

	LD R0, 1
	LD R1, 1
	ADD R0, R1	; reset Carry Flag

	POPF		; pop Carry Flag (this does not work)

	JCS MAIN	; jump on set Carry Flag

	JR MAIN		; this jump should never be reached
```

Best!
Alex

**Comment by MalteT** [comment]
Thanks, Alex!

Well, I tried your example, but it seems to work for me using version `6.1.0`. What `2a-emulator --version` is your student using?
I both tested your example and this modified version, which would make a misbehaviour more explicit:
```asm
#! mrasm

	LDSP 0xEF	; Load stack pointer, to enable calls
	CLR R0		; Clear register 0

MAIN:
	LD R0, 1
	LSR R0		; set Carry Flag

	PUSHF		; push Carry Flag

	LD R0, 1
	LD R1, 1
	ADD R0, R1	; reset Carry Flag

	POPF		; pop Carry Flag (this does not work)

	JCS MAIN	; jump on set Carry Flag

	CALL OH_NO      ; this jump should never be reached

OH_NO:
        STOP            ; Just halt
```
This never halts for me, though.

**Comment by MalteT** [comment]
I used an older version (`3.0.10`) which seems to indeed have that issue.

Best,
Malte

**Comment by AlexVonB** [comment]
Thanks for your quick response! We are using the most recent release on github, 5.0.0. Do you have all three builds for 6.x at hand? Otherwise I will build my own version and try it.

Thanks!
Alex

**Comment by MalteT** [comment]
Ah, yeah, I need to add another release for 6.x.
All three builds can be found here: https://github.com/MalteT/2a-emulator/actions/runs/210827880
I'll try to add an official release by the end of the day :)

Let me know if you can confirm, that POPF isn't a problem in 6.x anymore, please.

**Comment by AlexVonB** [comment]
Perfect, thank you! I tested the link from the readme and this one, but the artifacts in the runners are non-clickable and non-downloadable by me:

![grafik](https://user-images.githubusercontent.com/7325664/101362814-e8683b80-38a0-11eb-84da-260e26edffd1.png)

**Comment by MalteT** [comment]
I see. Well, after three commits, I managed to redo the artificats every week. The updated binaries should be online in about 10 minutes, I hope.

**Comment by AlexVonB** [comment]
OK so we built master and there POPF works like it should. The artifacts are not downloadable by me, maybe those are restricted to project members. We'll wait for the release binaries, thank you! And thank you for your very quick help!

**Comment by MalteT** [comment]
Happy it worked in the end! Thanks for the issue report, I'll add a new release in a moment.
