### ISSUE TITLE
Replace `2a-emulator test` with `2a-emulator run`

### ISSUE THREAD

**Issue by MalteT** [MalteT/2a-emulator#37]
I originally created the emulator with a simple testing feature, where you could write tests for programs. Like this:

File calc-42.test:
```
TEST 'calc 42'
FOR 1000
EXPECT FF = 0x2A, NO STOP
END
```

```console
$ 2a-emulator test some-program.asm calc-42.test
```
would then run the program and verify that it actually outputs 0x2A on output register FF and did not halt for 1000 cycles.

This can also be done using the `run` and `verify` subcommands:
```console
$ 2a-emulator run some-program.asm 1000 verify --ff 0x2A --state running
```

The former approach has some issues:
  - Introduction of a new syntax and fileformat
  - You can actually create non-deterministic test (not the fuzzy kind)

I personally don't see any issues with the latter approach. There's none of the drawbacks and, if so desired, one can easily extend this to test a lot of solutions easily.

Here's another example:
```console
$ 2a-emulator run add-fc-fd.asm 1000 --fc 12 --fd 32 verify --ff 44 --state running
```

But, of course, assuming someone did actually use the `2a-emulator test` functionality, they would experience a breaking change. So before starting this, I would like to hear your opinions/get your approval, @AlexVonB, @braungardt (approved).

**Comment by AlexVonB** [comment]
Hi Malte!
We did not use the tests at all, so we won't veto either of the options.
Best!

**Comment by MalteT** [comment]
The following options are still missing in `2a-emulator run ... verify ...`

- [x] `--reset CYCLE` to reset the machine before cycle CYCLE
- [x] `--interrupt CYCLE` to interrupt the machine before cycle CYCLE

I should also:
- [x] Update the README

**Comment by MalteT** [comment]
Done in 194fefe976fde4c3f24fae43e5ba7964f5da5e7a
