### ISSUE TITLE
Show Crash Report when `load`ing files

### ISSUE THREAD

**Issue by AlexVonB** [MalteT/2a-emulator#48]
Hi!

When loading and running a file that leads to a panick and a crash, the error message is not displayed when working in interactive mode. Minimal example:

```asm
#! mrasm
DEC (0xF1)
 ```

This leads to

```
 .\2a-emulator-x86_64-pc-windows-msvc.exe run file.asm 10000
thread 'main' panicked at 'not implemented: DEC [something other than R*] does not work yet', emulator-2a-lib\src\compiler.rs:184:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

on the command line with `run`, but just closes the interactive mode without notice or stack trace.

Quickest hack could be a log file, but I'm open to suggestions :)

Thanks!
Alex

**Comment by MalteT** [comment]
Hey, Alex!
Thanks for the issue!

this seems to be a much worse case of #11 (see also #12). Logging should actually work okay. The real problem I see here are these two `unimplemented!` calls in compiler.rs:
https://github.com/MalteT/2a-emulator/blob/741632e72f4e22e91535655fa79efc045bc407c5/emulator-2a-lib/src/compiler.rs#L184
https://github.com/MalteT/2a-emulator/blob/741632e72f4e22e91535655fa79efc045bc407c5/emulator-2a-lib/src/compiler.rs#L509

These are ugly fixes for two parser bugs..


An easy fix would be to customize the panic hook to catch all panics and log them correctly before the program crashes. Seems to be easy enough using https://doc.rust-lang.org/std/panic/fn.set_hook.html.

I've created #49 and #50 to track the above panic sources.

**Comment by MalteT** [comment]
The CI is happy with 5674baa51c4e7d62de02ca5dad9d0602a53f0540. This should work on the `develop`-Branch now. :)

I won't merge into the `main`-Branch until the end of the semester, though.

Please reopen if you find any problems with the current solution!
