### ISSUE TITLE
TST increases Register

### ISSUE THREAD

**Issue by AlexVonB** [MalteT/2a-emulator#51]
Hi!

This minimal program increases R0 when `TST`ing it, only if R2 is loaded with 1 (and behaves differently when 2, 3, or somethin other is loaded into R2):

```asm
#! mrasm

MAIN:
	LD R2, 0x01
	TST R0
	JR MAIN
```

We are in the process of verifying this on the real machine, but until then this oddity deserves an issue :D 

Best, Alex

**Comment by MalteT** [comment]
Thanks, Alex! Let me know, when you've done the testing. This seems very odd indeed 😁

**Comment by AlexVonB** [comment]
I think I found the error:

https://github.com/MalteT/2a-emulator/blob/4d3a61d8a8636080b47048cb3a05d82dacdb4926/emulator-2a-lib/src/compiler.rs#L193

According to the script, `TST` has the code `0100.10.rn`, but the implementation uses `0110.10.rn` which is an `ADD` with hard coded register `10` aka `R2`. If `R2` is `0`, ADD acts just like `TST`, but as soon as `R2` is filled, it just adds whatever is in `R2` onto `rn`. I tested this theory in the emulator with different values in `R2` and indeed it just adds whatever is in R2 onto the other register that should be tested.

I did not get to test it on the real machine yet, but I think it's just an bitflip here :)

**Comment by MalteT** [comment]
Yeah! 🥳 
Thanks for digging through this, Alex. I'll fix it and add some tests!

**Comment by MalteT** [comment]
Okay, it should be fixed now. This was actually much more painful than I anticipated. The bitflip was easy, but I managed to write a horrible test that almost made me believe that `72 == 48` until I realized that it's probably 0x48..

Well, have a nice weekend, @AlexVonB! And thanks for taking the time to find and report this bug!
