### ISSUE TITLE
State after reset differs from initial state

### ISSUE THREAD

**Issue by MalteT** [MalteT/2a-emulator#8]
The state of the machine after a reset is out of sync with the default state with which the machine is initialised. This includes at least the following settings:

- `TEMP`
- Jumper `J2`

**Comment by ghost** [comment]
We also hit this issue yesterday. Due to the way a program is loaded (nearly) everything get reset (see https://github.com/MalteT/2a-emulator/blob/1d75f1345ef3bfc95e786d642f0d78ad5f47b302/src/lib/machine/mod.rs#L284-L293

This does lead to  `rawmachine::reset()` here (shown below), where the description is wrong where it says it does not delete anything on the bus, since `bus.reset()` resets output_reg, micr, misr and the external board https://github.com/MalteT/2a-emulator/blob/1d75f1345ef3bfc95e786d642f0d78ad5f47b302/src/lib/machine/raw/mod.rs#L194-L214

Now we land in `board::reset()` where we get the problem. This reset temp and dasr/j2. https://github.com/MalteT/2a-emulator/blob/1d75f1345ef3bfc95e786d642f0d78ad5f47b302/src/lib/machine/board.rs#L442-L454

Possible solutions would be to:
 - not reset temp and dasr
 - not reset temp and to only reset specific flags of dasr (currently it is not set to empty but to only have the j2 flag)
 - reset to machine-init values (values which were given per command line)

Is there any of these that you would prefer? 

cc @AlexVonB

**Comment by AlexVonB** [comment]
Adding the idea to reset the temp consistently to either 0 or something "even" like 1.250000000. The current pi/2 is displayed as 1.57 and confuses the user.

**Comment by MalteT** [comment]
Thanks, @GrChristoph for the ideas!
Iirc, I inteded "reset" to be the "soft reset" that is equivalent to the reset done by the real machine whenever the Reset-button is pressed. If we agree on that notion,

- the temperature should not be touched by a reset
- the jumpers should be unchanged
- the RAM won't be touched
- and if we don't touch the above, the DASR shouldn't change either

But that doesn't work for loading a new program, since the RAM needs to be reset which invalidates the DASR (and possibly other registers aswell).

Ideally, we would have 3 different resets:
- Soft reset (above), executed when CTRL+R is hit
- New_program_reset, that is executed, when a new program is loaded
- Hard reset, as done by the real machine (left side) whenever the emulator 2a image is loaded. This one should reset everything to the initial state, which should be the same as the initial state after a call to `2a-emulator interactive` (without adding arguments). Jumpers should probably be untouched even by this reset.

And then, ~~of course~~ realistically, the New_program_reset, executes at least the soft reset and the hard reset executes at least the New_program_reset.

It's been on my todo list since I finished the thesis to actually test these different resets on the real machine, but due to the current situation, I might have to rely on the documentation Werner Dreher gave me. Let me know, if you have any additional ideas. It might be a smart idea to assemble a list of all items that belong to the state, if we intent to do this the right way.



@AlexVonB, I don't remember if `set temp = x.xx` actually floors/rounds the value x.xx to anything sane (i.e. 0.01), that might need some attention aswell. But I agree, pi/2 has to go.

**Comment by AlexVonB** [comment]
One last related bug: `--temp x.xx` does not change the temperature when starting the interactive mode. This is probably going to get resolved during the course of this issue, but now it is in writing, too.

**Comment by MalteT** [comment]
What I've found so far. This doesn't mention the defaults/init values for things, but I haven't found any non-zero defaults. Since the university will be closed until at least the 10th, it'll take some time to remove the rest of the unknowns. I guess I'll try to fix the `--temp` issue and the confusing defaults first.

# Resets

## A: CPU Reset (Soft Reset)
This is executed when CTRL+R is hit. The Reset-Button executes this.

## B: Program Reset
Will be executed when a new program is loaded. ~~Since the docs don't mention this, it'll probably coincide with the CPU Reset + Ram Reset.~~ This seems to be Master Reset + Ram reset.

## C: Master Reset (Hard Reset)
This is the reset that is executed on boot of the real machine and effectively defines how the default machine should look.

## Defaults
Everything should get zeroed.

## State of the Machine (according to the Emulator)
- ?: TBD
- !: Never reset!
- #: Depends on other things and will reset ~~correctly by default~~ according to my code

| Name                                       | Ty | Notes                                                |
| ------------------------------------------ | -- | ---------------------------------------------------- |
| `··StepMode`                               | !  | It's an external switch, user operated               |
| `··RawMachine `                            |    |                                                      |
| `····MicroprogramRam `                     | A  |                                                      |
| `······current_index (address) `           | .  |                                                      |
| `····Register `                            | A  |                                                      |
| `······content `                           | .  |                                                      |
| `····InstructionRegister `                 | A  |                                                      |
| `······content `                           | .  |                                                      |
| `····Bus `                                 |    |                                                      |
| `······ram `                               | B  | not reset if mcontrol receives --NO-FILL             |
| `······input_reg `                         | C  |                                                      |
| `······output_reg `                        | A  |                                                      |
| `······MICR `                              | A  |                                                      |
| `········*_INTERRUPT_ENABLE `              | .  |                                                      |
| `······MISR `                              | #  |                                                      |
| `········*_INTERRUPT_PENDING `             | #  | The reset of the MICR will reset *_INTERRUPT_PENDING |
| `········*_INTERRUPT_ACTIVE `              | #  | depends on respective interrupt sources              |
| `······UCR `                               | A  |                                                      |
| `········INT_ON_RX_READY `                 | .  |                                                      |
| `········INT_ON_RX_FULL `                  | .  |                                                      |
| `········INT_ON_TX_EMPTY `                 | .  |                                                      |
| `········INT_ON_TX_READY `                 | .  |                                                      |
| `········IGNORE_CTS `                      | .  |                                                      |
| `······USR `                               | #  |                                                      |
| `········TX_READY `                        | #  |                                                      |
| `········TX_EMPTY `                        | #  |                                                      |
| `········NOT_CTS `                         | #  |                                                      |
| `········TX_D `                            | #  |                                                      |
| `········RX_D `                            | #  |                                                      |
| `········NOT_RTS `                         | #  |                                                      |
| `········RX_FULL `                         | #  |                                                      |
| `········RX_READY `                        | #  |                                                      |
| `······uart_send `                         | ?  | The UART isn't actually working atm                  |
| `······uart_recv `                         | ?  |                                                      |
| `······int_timer `                         | C  | CPU Reset resets the time but not the config         |
| `········enabled `                         | .  |                                                      |
| `········div1-3 `                          | .  |                                                      |
| `······Board `                             |    |                                                      |
| `········digital_input1 `                  | !  | (extern)                                             |
| `········digital_output1 `                 | C  |                                                      |
| `········digital_output2 `                 | C  |                                                      |
| `········temp `                            | !  | (extern)                                             |
| `········DASR `                            |    |                                                      |
| `··········J2 `                            | !  | (extern)                                             |
| `··········J1 `                            | !  | (extern)                                             |
| `··········FAN `                           | #  | depends on ram[0x??]                                 |
| `··········COMP_DAC2 `                     | #  | depends on ram[0x??] and temp                        |
| `··········COMP_DAC1 `                     | #  | depends on ram[0x??] and analog_input1               |
| `··········UIO_3 `                         | !  | (extern)                                             |
| `··········UIO_2 `                         | !  | (extern)                                             |
| `··········UIO_1 `                         | !  | (extern)                                             |
| `········DAISR `                           | #  |                                                      |
| `··········INTURRUPT_PENDING `             | #  |                                                      |
| `··········INTURRUPT_REQUESTED `           | #  |                                                      |
| `··········INTERRUPT_FF `                  | #  |                                                      |
| `··········SOURCE `                        | #  |                                                      |
| `········DAICR `                           | C  |                                                      |
| `··········IE `                            | .  |                                                      |
| `··········EDGE `                          | .  |                                                      |
| `··········FALLING `                       | .  |                                                      |
| `··········INT_SOURCE2-0 `                 | .  |                                                      |
| `········analog_inputs `                   | !  |                                                      |
| `········analog_outputs `                  | C  |                                                      |
| `········fan_rpm `                         | C  | depends on ram[0x??]                                 |
| `········uio_dir `                         | C  |                                                      |
| `····pending_register_write `              | A  |                                                      |
| `····pending_flag_write `                  | A  |                                                      |
| `····pending_edge_interrupt `              | A  |                                                      |
| `····pending_level_interrupt `             | #  | depends on all interrupt sources                     |
| `····State (Running/Stopped/ErrorStopped)` | A  |                                                      |
| `····pending_wait_for_memory `             | A  |                                                      |
| `····AluOutput `                           | A  |                                                      |
| `····Stacksize `                           | !  | will be updated when loading a new program           |
| `····last_bus_read `                       | A  |                                                      |

**Comment by MalteT** [comment]
Everything but the status registers should be working now, those will be fixed with #34. Temperature should now be (re)set to zero. I couldn't reproduce the `--temp x.x` issue, but I tested it and it seems to work now.
